-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.admin (
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text,
  email text,
  id uuid NOT NULL UNIQUE,
  role text DEFAULT 'admin'::text,
  CONSTRAINT admin_pkey PRIMARY KEY (id)
);
CREATE TABLE public.admin_notifications_settings (
  id uuid NOT NULL,
  user_registration_notification boolean,
  user_account_suspensions_notification boolean,
  user_profile_verfication_request boolean,
  payment_disput boolean,
  revenue_milstone boolean,
  payout_processing boolean,
  low_mentor_ratings boolean,
  session_cancellation boolean,
  review_flagging boolean,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT admin_notifications_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.availability_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  mentor_id uuid DEFAULT auth.uid(),
  message text,
  api text,
  availability_change jsonb,
  pervious_availablity jsonb,
  role text,
  CONSTRAINT availability_logs_pkey PRIMARY KEY (id),
  CONSTRAINT availability_logs_mentor_id_fkey FOREIGN KEY (mentor_id) REFERENCES public.mentors_new(id)
);
CREATE TABLE public.booking_temp (
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  transaction_id text,
  booking_data jsonb,
  id uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  CONSTRAINT booking_temp_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bookings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  meeting_type_id uuid,
  invitee_name text,
  invitee_email text,
  start_time timestamp with time zone,
  end_time timestamp with time zone,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT now(),
  notes text,
  cancelled_at timestamp with time zone,
  meeting_provider text CHECK (meeting_provider = ANY (ARRAY['daily'::text, 'offline'::text])),
  meeting_url text,
  meeting_id character varying,
  meeting_password character varying,
  host_url text,
  event_id character varying,
  calendar_link text,
  meeting_key character varying,
  meeting_creation_error text,
  recording_url text,
  recording_updated_at timestamp with time zone,
  resume text,
  invitee_phone text,
  org_id text,
  mentee_meeting_url text,
  is_completed boolean,
  practice_interview_selected_questions jsonb,
  batch text,
  institution text,
  payment_status text,
  transaction_id text,
  feedback_response jsonb,
  report_url text,
  transcript text,
  jd_url text,
  transcript_updated_at timestamp with time zone,
  chats jsonb,
  request_payout boolean DEFAULT false,
  initiate_payout boolean DEFAULT false,
  meeting_done boolean,
  amount text,
  interview_duration text,
  practice_interview_selected_domain text,
  event_type text,
  is_feedback_submitted boolean DEFAULT false,
  is_read boolean DEFAULT false,
  opportunity_id uuid,
  format_of_session text,
  is_deleted boolean DEFAULT false,
  student_id uuid,
  payment_mode text,
  easebuzz_payment_id text,
  payout_completed_by_admin boolean DEFAULT false,
  program text,
  CONSTRAINT bookings_pkey PRIMARY KEY (id),
  CONSTRAINT bookings_meeting_type_id_fkey FOREIGN KEY (meeting_type_id) REFERENCES public.meeting_types(id),
  CONSTRAINT bookings_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.mentors_new(id),
  CONSTRAINT bookings_opportunity_id_fkey FOREIGN KEY (opportunity_id) REFERENCES public.mentor_opportunities(id),
  CONSTRAINT bookings_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students_new(id)
);
CREATE TABLE public.bookings_duplicate (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  meeting_type_id uuid,
  invitee_name text NOT NULL,
  invitee_email text NOT NULL,
  start_time timestamp with time zone NOT NULL,
  end_time timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT now(),
  notes text,
  cancelled_at timestamp with time zone,
  meeting_provider character varying DEFAULT 'zoom'::character varying CHECK (meeting_provider::text = ANY (ARRAY['daily'::text, 'offline'::text])),
  meeting_url text,
  meeting_id character varying,
  meeting_password character varying,
  host_url text,
  event_id character varying,
  calendar_link text,
  meeting_key character varying,
  meeting_creation_error text,
  recording_url text,
  recording_updated_at timestamp with time zone,
  resume text,
  invitee_phone text,
  org_id text,
  mentee_meeting_url text,
  is_completed boolean,
  practice_interview_selected_questions jsonb,
  batch text,
  institution text,
  payment_status text,
  transaction_id text,
  feedback_response jsonb,
  report_url text,
  transcript text,
  jd_url text,
  transcript_updated_at text,
  chats jsonb,
  request_payout boolean DEFAULT false,
  initiate_payout boolean DEFAULT false,
  meeting_done boolean,
  amount text,
  interview_duration text,
  practice_interview_selected_domain text,
  event_type text,
  is_feedback_submitted boolean DEFAULT false,
  is_read boolean DEFAULT false,
  opportunity_id uuid,
  format_of_session text,
  CONSTRAINT bookings_duplicate_pkey PRIMARY KEY (id),
  CONSTRAINT bookings_duplicate_meeting_type_id_fkey FOREIGN KEY (meeting_type_id) REFERENCES public.meeting_types(id),
  CONSTRAINT bookings_duplicate_opportunity_id_fkey FOREIGN KEY (opportunity_id) REFERENCES public.mentor_opportunities(id),
  CONSTRAINT bookings_duplicate_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.mentors_new(id)
);
CREATE TABLE public.cdm_batches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  institute_id uuid,
  proposal_id uuid,
  name text NOT NULL,
  status text DEFAULT 'Tentative'::text,
  start_date date,
  end_date date,
  schedule_description text,
  mentor_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  department text,
  CONSTRAINT cdm_batches_pkey PRIMARY KEY (id),
  CONSTRAINT cdm_batches_institute_id_fkey FOREIGN KEY (institute_id) REFERENCES public.cdm_institutes(id),
  CONSTRAINT cdm_batches_mentor_id_fkey FOREIGN KEY (mentor_id) REFERENCES public.mentors(id)
);
CREATE TABLE public.cdm_institute_pocs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  institute_id uuid,
  full_name text NOT NULL,
  email text,
  phone text,
  designation text,
  is_primary_contact boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  user_id uuid UNIQUE,
  CONSTRAINT cdm_institute_pocs_pkey PRIMARY KEY (id),
  CONSTRAINT cdm_institute_pocs_institute_id_fkey FOREIGN KEY (institute_id) REFERENCES public.cdm_institutes(id),
  CONSTRAINT cdm_institute_pocs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.cdm_institutes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  code text UNIQUE,
  location text,
  logo_url text,
  website_url text,
  status text DEFAULT 'Active'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cdm_institutes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cdm_journey_item_mentors (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  journey_item_id uuid,
  mentor_id uuid,
  CONSTRAINT cdm_journey_item_mentors_pkey PRIMARY KEY (id),
  CONSTRAINT cdm_journey_item_mentors_journey_item_id_fkey FOREIGN KEY (journey_item_id) REFERENCES public.cdm_learning_journey_items(id),
  CONSTRAINT cdm_journey_item_mentors_mentor_id_fkey FOREIGN KEY (mentor_id) REFERENCES public.mentors(id)
);
CREATE TABLE public.cdm_journey_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  journey_item_id uuid,
  mentor_id uuid,
  scheduled_date timestamp with time zone,
  meeting_link text,
  status text DEFAULT 'Pending'::text,
  recording_link text,
  session_type text DEFAULT '1:1'::text,
  journey_item_name text,
  CONSTRAINT cdm_journey_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT cdm_journey_sessions_journey_item_id_fkey FOREIGN KEY (journey_item_id) REFERENCES public.cdm_learning_journey_items(id),
  CONSTRAINT cdm_journey_sessions_mentor_id_fkey FOREIGN KEY (mentor_id) REFERENCES public.mentors(id)
);
CREATE TABLE public.cdm_learning_journey_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  learning_journey_id uuid,
  product_id uuid,
  particulars text,
  product_code text,
  delivery_mode text,
  format text,
  total_hours numeric,
  student_count integer,
  num_sessions integer,
  start_date date,
  end_date date,
  status text DEFAULT 'Yet to Schedule'::text,
  average_rating numeric DEFAULT 0.00,
  sequence_order integer DEFAULT 1,
  CONSTRAINT cdm_learning_journey_items_pkey PRIMARY KEY (id),
  CONSTRAINT cdm_learning_journey_items_learning_journey_id_fkey FOREIGN KEY (learning_journey_id) REFERENCES public.cdm_learning_journeys(id),
  CONSTRAINT cdm_learning_journey_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.cdm_products(id)
);
CREATE TABLE public.cdm_learning_journeys (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  proposal_id uuid,
  institute_id uuid,
  batch_id uuid,
  status text DEFAULT 'Active'::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cdm_learning_journeys_pkey PRIMARY KEY (id),
  CONSTRAINT cdm_learning_journeys_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES public.cdm_batches(id),
  CONSTRAINT cdm_learning_journeys_institute_id_fkey FOREIGN KEY (institute_id) REFERENCES public.cdm_institutes(id),
  CONSTRAINT cdm_learning_journeys_proposal_id_fkey FOREIGN KEY (proposal_id) REFERENCES public.cdm_proposals(id)
);
CREATE TABLE public.cdm_modules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  category text NOT NULL CHECK (category = ANY (ARRAY['Clarity'::text, 'Prep'::text, 'Last-mile Prep'::text])),
  category_code text CHECK (category_code = ANY (ARRAY['ORN'::text, 'ASM'::text, 'WKS'::text, 'MCL'::text, 'PRP'::text, 'APT'::text, 'BCP'::text, 'LMH'::text, 'SIEP'::text, 'PMF'::text, 'LMS'::text])),
  description text,
  mode text NOT NULL CHECK (mode = ANY (ARRAY['1:1'::text, '1:M'::text, '1:8'::text, '1:10'::text])),
  delivery_type text NOT NULL CHECK (delivery_type = ANY (ARRAY['Offline'::text, 'Online'::text, 'Platform'::text, 'Offline/Online'::text])),
  indicative_timeline text,
  total_hours_per_student numeric,
  session_count integer DEFAULT 1,
  num_students integer DEFAULT 1,
  price_per_session_ctu numeric DEFAULT 0,
  ctc numeric NOT NULL DEFAULT 0,
  ctu numeric DEFAULT 0,
  price_per_student numeric DEFAULT 0,
  ctc_per_session numeric DEFAULT 0,
  margin numeric DEFAULT 0,
  margin_percentage numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cdm_modules_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cdm_products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  module_id uuid,
  particulars text NOT NULL,
  product_code text NOT NULL UNIQUE,
  delivery_mode text,
  format text,
  total_hours numeric,
  max_students integer,
  num_sessions integer,
  ctc_per_session numeric,
  asking_price_per_session numeric,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cdm_products_pkey PRIMARY KEY (id),
  CONSTRAINT cdm_products_module_id_fkey FOREIGN KEY (module_id) REFERENCES public.cdm_modules(id)
);
CREATE TABLE public.cdm_proposal_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  proposal_id uuid,
  product_id uuid,
  sequence_order integer NOT NULL DEFAULT 1,
  tentative_start_date date,
  tentative_end_date date,
  student_count integer NOT NULL,
  quoted_price_per_session numeric,
  snapshot_particulars text,
  snapshot_product_code text,
  snapshot_delivery_mode text,
  snapshot_max_students integer,
  snapshot_ctc_per_session numeric,
  num_sessions integer,
  total_ctc numeric,
  total_asking_price numeric,
  created_at timestamp with time zone DEFAULT now(),
  snapshot_format text,
  snapshot_total_hours numeric,
  CONSTRAINT cdm_proposal_items_pkey PRIMARY KEY (id),
  CONSTRAINT cdm_proposal_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.cdm_products(id),
  CONSTRAINT cdm_proposal_items_proposal_id_fkey FOREIGN KEY (proposal_id) REFERENCES public.cdm_proposals(id)
);
CREATE TABLE public.cdm_proposals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  proposal_ref_id text UNIQUE,
  institute_id uuid NOT NULL,
  batch_id uuid NOT NULL,
  status text DEFAULT 'Draft'::text,
  discount_percentage numeric DEFAULT 0,
  gst_percentage numeric DEFAULT 18.00,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cdm_proposals_pkey PRIMARY KEY (id),
  CONSTRAINT cdm_proposals_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES public.cdm_batches(id),
  CONSTRAINT cdm_proposals_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.tcc_admins(id),
  CONSTRAINT cdm_proposals_institute_id_fkey FOREIGN KEY (institute_id) REFERENCES public.cdm_institutes(id)
);
CREATE TABLE public.cdm_session_attendees (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL,
  student_id uuid NOT NULL,
  attendance_status text DEFAULT 'Pending'::text,
  is_report_generated boolean DEFAULT false,
  feedback_data jsonb DEFAULT '{}'::jsonb,
  student_name text,
  batch_name text,
  session_name text,
  CONSTRAINT cdm_session_attendees_pkey PRIMARY KEY (id),
  CONSTRAINT cdm_attendees_session_fkey FOREIGN KEY (session_id) REFERENCES public.cdm_journey_sessions(id),
  CONSTRAINT cdm_attendees_student_fkey FOREIGN KEY (student_id) REFERENCES public.cdm_students(id)
);
CREATE TABLE public.cdm_student_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid,
  report_type text NOT NULL,
  report_data jsonb,
  created_at timestamp with time zone DEFAULT now(),
  student_name text,
  batch_name text,
  attendee_id uuid NOT NULL,
  CONSTRAINT cdm_student_reports_pkey PRIMARY KEY (id),
  CONSTRAINT cdm_student_reports_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.cdm_journey_sessions(id),
  CONSTRAINT cdm_reports_attendee_fkey FOREIGN KEY (attendee_id) REFERENCES public.cdm_session_attendees(id)
);
CREATE TABLE public.cdm_students (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  batch_id uuid,
  email text,
  phone text,
  full_name text NOT NULL,
  gender text,
  enrollment_id text UNIQUE,
  CONSTRAINT cdm_students_pkey PRIMARY KEY (id),
  CONSTRAINT cdm_students_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES public.cdm_batches(id)
);
CREATE TABLE public.companies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_email text,
  company_phone text,
  company_profile_url text,
  company_name text,
  company_type text,
  company_industry_type text,
  company_founded_year text,
  company_size text,
  company_website text,
  company_description text,
  company_cin_no text,
  company_gst_no text,
  company_pan_no text,
  company_tan_no text,
  company_reg_no text,
  company_state_of_reg text,
  company_registered_address text,
  company_registered_city text,
  company_registered_state text,
  company_registered_pincode text,
  company_poc_name text,
  company_poc_designation text,
  company_poc_email text,
  company_poc_phone text,
  company_hr_name text,
  company_hr_email text,
  company_hr_phone text,
  company_cin_url jsonb,
  company_gst_url jsonb,
  company_pan_url jsonb,
  company_address_proof_url jsonb,
  type_of_talent ARRAY,
  type_of_institutions ARRAY,
  budget_range_for_hiring text,
  immediate_hiring_requirements text,
  is_delete boolean DEFAULT false,
  is_suspended boolean DEFAULT false,
  suspended_duration text,
  basic_information_step_1 boolean DEFAULT true,
  legal_compliance_step_2 boolean DEFAULT true,
  contact_address_step_3 boolean DEFAULT true,
  documents_step_4 boolean DEFAULT true,
  preference_step_5 boolean DEFAULT true,
  company_operational_address text,
  company_operational_city text,
  company_operational_state text,
  company_operational_pincode text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  company_verification text DEFAULT 'Pending'::text,
  interested_institutes ARRAY,
  CONSTRAINT companies_pkey PRIMARY KEY (id)
);
CREATE TABLE public.company_activities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  title text,
  company_id uuid,
  description text,
  CONSTRAINT company_activities_pkey PRIMARY KEY (id)
);
CREATE TABLE public.conversations (
  id uuid NOT NULL,
  ticket_id uuid,
  send_by uuid,
  send_to uuid,
  send_time timestamp without time zone,
  massage text,
  is_read boolean,
  attach_file_url text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT conversations_pkey PRIMARY KEY (id),
  CONSTRAINT conversations_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES public.tickets(id)
);
CREATE TABLE public.enhance_resumes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  enhance_resume_data jsonb,
  job_description text,
  static_temp_id uuid DEFAULT gen_random_uuid(),
  student_id uuid DEFAULT gen_random_uuid(),
  ats_score text,
  title text,
  CONSTRAINT enhance_resumes_pkey PRIMARY KEY (id),
  CONSTRAINT enhance_resumes_static_temp_id_fkey FOREIGN KEY (static_temp_id) REFERENCES public.static_resume_template(id),
  CONSTRAINT enhance_resumes_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students_new(id)
);
CREATE TABLE public.form_ans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  student_info text,
  formdata jsonb,
  link text,
  form_slug text,
  session_id uuid,
  mentor_id uuid,
  mentor_name text,
  email_sent boolean DEFAULT false,
  CONSTRAINT form_ans_pkey PRIMARY KEY (id)
);
CREATE TABLE public.form_ans_duplicate (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  student_info text,
  formdata jsonb,
  link text,
  form_slug text,
  session_id uuid,
  mentor_id uuid,
  mentor_name text,
  email_sent boolean,
  CONSTRAINT form_ans_duplicate_pkey PRIMARY KEY (id)
);
CREATE TABLE public.formbuilder_email_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL,
  student_name text NOT NULL,
  form_type text NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['sent'::text, 'failed'::text])),
  error_message text,
  message_id text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  mentor_name text,
  slug text,
  CONSTRAINT formbuilder_email_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.forms (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text,
  description text,
  json jsonb,
  slug text UNIQUE,
  org_id uuid,
  form_type text,
  role text DEFAULT ''::text,
  is_student boolean DEFAULT false,
  CONSTRAINT forms_pkey PRIMARY KEY (id),
  CONSTRAINT forms_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.google_industry_update (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  thumbnail text,
  title text,
  publisher text,
  snippet text,
  newsUrl text,
  published text,
  CONSTRAINT google_industry_update_pkey PRIMARY KEY (id)
);
CREATE TABLE public.indusrty_updates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text,
  tags ARRAY,
  posting_date text,
  discription text,
  cover_image_url text,
  author text,
  category text,
  status text,
  is_published boolean,
  is_scheduled boolean,
  scheduled_time text,
  is_delete boolean,
  views ARRAY,
  enagagement ARRAY,
  is_draft boolean,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT indusrty_updates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.institutions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  institute_name text,
  institute_reviews text,
  institute_school_type text,
  institute_location text,
  institute_type text,
  institute_about text,
  institute_established_year text,
  institute_rating text,
  institute_nirf_rating text,
  institute_tier text,
  institute_placement_rate text,
  institute_average_package text,
  institute_highest_package text,
  institute_company_visted_count text,
  institute_total_student text,
  institute_accreditation ARRAY,
  institute_student_faculty_ratio text,
  institute_facilities ARRAY,
  institute_placement_statistics json,
  institute_industry_wise_placements json,
  institute_programs json,
  institute_top_recruiters json,
  institute_faculty_information json,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  is_delete boolean DEFAULT false,
  CONSTRAINT institutions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.institutions_duplicate (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  institute_name text,
  institute_reviews text,
  institute_school_type text,
  institute_location text,
  institute_type text,
  institute_about text,
  institute_established_year text,
  institute_rating text,
  institute_nirf_rating text,
  institute_tier text,
  institute_placement_rate text,
  institute_average_package text,
  institute_highest_package text,
  institute_company_visted_count text,
  institute_total_student text,
  institute_accreditation ARRAY,
  institute_student_faculty_ratio text,
  institute_facilities ARRAY,
  institute_placement_statistics json,
  institute_industry_wise_placements json,
  institute_programs json,
  institute_top_recruiters json,
  institute_faculty_information json,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  is_delete boolean DEFAULT false,
  CONSTRAINT institutions_duplicate_pkey PRIMARY KEY (id)
);
CREATE TABLE public.job_applications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_id uuid,
  student_id uuid,
  resume_url text,
  cover_letter text,
  show_interest boolean,
  status text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  is_applied boolean DEFAULT false,
  is_shortlisted boolean,
  is_interviewed boolean,
  is_rejected boolean,
  CONSTRAINT job_applications_pkey PRIMARY KEY (id),
  CONSTRAINT job_applications_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id),
  CONSTRAINT job_applications_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students_new(id)
);
CREATE TABLE public.job_interview_trackings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_id uuid,
  interview_tracking text,
  result text,
  interviewer_id text,
  interview_rating text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  interview_type text,
  interview_date date,
  interview_time time without time zone,
  duration_minutes integer,
  interviewer_emails ARRAY,
  meeting_link text,
  interview_notes text,
  ats_score text,
  skills_match text,
  experience text,
  application_id uuid,
  company_id uuid,
  is_hired boolean DEFAULT false,
  is_completed boolean DEFAULT false,
  status text,
  location text,
  provider text,
  mentee_url text,
  mentor_url text,
  interview_round text,
  recording text,
  phone_no text,
  student_phone text,
  rating text,
  CONSTRAINT job_interview_trackings_pkey PRIMARY KEY (id),
  CONSTRAINT job_interview_trackings_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id),
  CONSTRAINT job_interview_trackings_application_id_fkey FOREIGN KEY (application_id) REFERENCES public.job_applications(id),
  CONSTRAINT job_interview_trackings_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_title text,
  created_by uuid,
  job_location text,
  job_department text,
  job_experience_level text,
  job_salary_range text,
  about_this_role text,
  job_key_responsibility ARRAY,
  job_required_skills ARRAY,
  job_required_qualifications ARRAY,
  job_prefered_qualifications ARRAY,
  job_benefits_perks jsonb,
  job_hiring_manager_information json,
  job_start_date text,
  job_end_date text,
  is_active boolean DEFAULT true,
  is_draft boolean,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  is_delete boolean DEFAULT false,
  company_info jsonb,
  job_type text,
  job_status text,
  apify_id text,
  job_url text,
  is_featured boolean,
  industry_key text,
  ai_classification_confidence numeric,
  ai_classified_at timestamp without time zone,
  ai_classification_metadata jsonb,
  job_views text,
  CONSTRAINT jobs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.meeting (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  mentor_id uuid,
  student_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  feedback_report jsonb,
  CONSTRAINT meeting_pkey PRIMARY KEY (id),
  CONSTRAINT meeting_mentor_id_fkey FOREIGN KEY (mentor_id) REFERENCES public.users(id),
  CONSTRAINT meeting_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.users(id)
);
CREATE TABLE public.meeting_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  name text NOT NULL,
  description text,
  duration_minutes integer NOT NULL,
  buffer_time integer DEFAULT 0,
  slug text NOT NULL,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT now(),
  default_meeting_provider character varying DEFAULT 'daily'::character varying CHECK (default_meeting_provider::text = 'daily'::text),
  meeting_provider_settings jsonb DEFAULT '{}'::jsonb,
  availability jsonb,
  min_notice text NOT NULL,
  CONSTRAINT meeting_types_pkey PRIMARY KEY (id),
  CONSTRAINT meeting_types_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.mentors_new(id)
);
CREATE TABLE public.mentor_opportunities (
  institute text,
  format_of_the_session text,
  location text,
  session_on text,
  batch text,
  batch_profile text,
  no_of_mentors_required bigint,
  remuneration_per_session bigint,
  no_of_sessions bigint,
  total_pay bigint,
  no_of_hour_commitment real,
  client_is_looking_for text,
  past_feedback text,
  sign_up_deadline text,
  urgency_flag text,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  date date,
  interested_mentors ARRAY,
  batch_website text,
  program_name text,
  created_at timestamp with time zone DEFAULT now(),
  domain_expertise ARRAY,
  functional_domain_expertise ARRAY,
  technical_skills ARRAY,
  soft_skills ARRAY,
  mentor_data ARRAY,
  short_listed_mentors ARRAY,
  hold_mentors ARRAY,
  rejected_mentors ARRAY,
  to_show boolean DEFAULT true,
  org_id uuid,
  from_date date,
  to_date date,
  is_hide boolean DEFAULT false,
  place_of_session text,
  is_completed boolean DEFAULT false,
  google_meet_link text,
  is_backdate_opportunity boolean DEFAULT false,
  status text,
  timeline text,
  confirmation_on_date_and_slot boolean,
  expectation_setting_call boolean,
  batch_profile_sent boolean,
  mentor_profile_sent_to_student boolean,
  email_sent_to_mentor boolean,
  who_is_giving_intro text,
  average_ratings text,
  student_ratings text,
  mentor_ratings text,
  recording_of_the_session text,
  sentiments text,
  recording_type text,
  CONSTRAINT mentor_opportunities_pkey PRIMARY KEY (id),
  CONSTRAINT mentor_opportunities_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.mentor_suggested_domains (
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  mentor_id uuid DEFAULT gen_random_uuid(),
  booking_id uuid DEFAULT gen_random_uuid(),
  domain_name text,
  id uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  CONSTRAINT mentor_suggested_domains_pkey PRIMARY KEY (id),
  CONSTRAINT mentor_suggested_domains_mentor_id_fkey FOREIGN KEY (mentor_id) REFERENCES public.mentors_new(id),
  CONSTRAINT mentor_suggested_domains_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);
CREATE TABLE public.mentors (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  profile_url text,
  first_name text,
  last_name text,
  email text UNIQUE,
  phone text,
  address text,
  pincode text,
  state text,
  country text,
  highest_qualification text,
  experience text,
  current_profile text,
  current_company_name text,
  resume_url text,
  description text,
  who_do_you_want_to_mentor ARRAY,
  prefer_mentoring_students_form ARRAY,
  interested_in ARRAY,
  time_can_you_commit_in_a_week text,
  linkedin_url text,
  other_links text,
  calendly_token text,
  calendly_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  industry ARRAY,
  domain_experties ARRAY,
  qualification_institution text,
  ac_holder_name text,
  bank_name text,
  account_no text,
  ifsc_code text,
  zoom_connect boolean DEFAULT false,
  CONSTRAINT mentors_pkey PRIMARY KEY (id),
  CONSTRAINT mentors_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.mentors_new (
  id uuid NOT NULL DEFAULT auth.uid(),
  mentor_email text UNIQUE,
  mentor_phone text,
  mentor_profile_url text,
  mentor_first_name text,
  mentor_last_name text,
  mentor_address text,
  mentor_city text,
  mentor_pincode text,
  mentor_state text,
  mentor_country text,
  mentor_about text,
  mentor_education json,
  mentor_work_experience json,
  mentor_resume_url text,
  mentor_domain_expertise ARRAY,
  mentor_technical_skills ARRAY,
  mentor_soft_skills ARRAY,
  mentor_certification json,
  mentor_languages json,
  mentor_who_do_you ARRAY,
  mentor_prefer_mentoring ARRAY,
  mentor_area_interest ARRAY,
  mentor_weekly_time text,
  mentor_earnings text,
  mentor_linkedin_url text,
  mentor_other_profile_url text,
  mentor_account_holder_name text,
  mentor_bank_name text,
  mentor_average_rating text,
  mentor_threshold_rating text,
  mentor_account_no text,
  mentor_ifsc_code text,
  mentor_weekly_availability json,
  mentor_access_token text,
  mentor_referesh_token text,
  is_delete boolean DEFAULT false,
  is_suspended boolean,
  suspended_duration text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  personal_draft boolean DEFAULT false,
  education_draft boolean DEFAULT false,
  skills_draft boolean DEFAULT false,
  service_payment_draft boolean DEFAULT false,
  username text,
  experience_years text,
  mentor_functional_domain_expertise ARRAY,
  gd_session boolean DEFAULT false,
  mentor_pan_number text,
  CONSTRAINT mentors_new_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL,
  notification_title text,
  notification_content text,
  notification_type text,
  notification_recipient text,
  notification_priority text,
  status boolean,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT notifications_pkey PRIMARY KEY (id)
);
CREATE TABLE public.opportunities_session_title (
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text,
  id uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  CONSTRAINT opportunities_session_title_pkey PRIMARY KEY (id)
);
CREATE TABLE public.organisations_student_list (
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text,
  email text,
  phone text,
  org_id uuid,
  id uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  CONSTRAINT organisations_student_list_pkey PRIMARY KEY (id),
  CONSTRAINT organisations_student_list_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  organization_name text,
  user_id text,
  email text,
  phone text,
  selected_mentors ARRAY,
  password text,
  user_name text,
  mentor_selected_by_org ARRAY,
  org_profile text,
  org_profile_base64 text,
  is_paid boolean NOT NULL DEFAULT false,
  is_deleted boolean DEFAULT false,
  CONSTRAINT organizations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.otp (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  otp text,
  email text,
  expires_at text,
  CONSTRAINT otp_pkey PRIMARY KEY (id)
);
CREATE TABLE public.project_applications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid,
  student_id uuid,
  resume_url text,
  cover_letter text,
  show_interest boolean,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  status text,
  industry_type text,
  is_interviewed boolean,
  is_shortlisted boolean,
  is_rejected boolean,
  CONSTRAINT project_applications_pkey PRIMARY KEY (id),
  CONSTRAINT project_applications_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT project_applications_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students_new(id)
);
CREATE TABLE public.project_interview_trackings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid,
  application_id uuid,
  interview_tracking text,
  result text,
  interviewer_id text,
  interview_rating text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  interview_type text,
  interview_date date,
  interview_time time without time zone,
  duration_minutes integer,
  interviewer_emails ARRAY,
  meeting_link text,
  interview_notes text,
  ats_score text,
  skills_match text,
  experience text,
  company_id uuid,
  is_hired boolean DEFAULT false,
  is_completed boolean DEFAULT false,
  location text,
  provider text,
  mentee_url text,
  mentor_url text,
  interview_round text,
  status text,
  recording text,
  phone_no text,
  student_phone text,
  rating text,
  CONSTRAINT project_interview_trackings_pkey PRIMARY KEY (id),
  CONSTRAINT project_interview_trackings_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT project_interview_trackings_application_id_fkey FOREIGN KEY (application_id) REFERENCES public.project_applications(id),
  CONSTRAINT project_interview_trackings_project_id_fkey1 FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT project_interview_trackings_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.projects (
  id uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  project_title text,
  created_by uuid,
  project_location text,
  project_department text,
  project_experience_level text,
  project_expenses text,
  about_this_project text,
  project_key_responsibility ARRAY,
  project_required_skills ARRAY,
  project_required_qualifications ARRAY,
  project_prefered_qualifications ARRAY,
  project_hiring_manager_information json,
  project_start_date text,
  project_end_date text,
  is_active boolean,
  is_draft boolean,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  is_delete boolean DEFAULT false,
  company_info jsonb,
  project_status text,
  project_duration text,
  is_featured boolean,
  project_views text,
  CONSTRAINT projects_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ratings_and_reviews (
  id uuid NOT NULL,
  given_by uuid,
  given_for uuid,
  review_text text,
  rating_text text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ratings_and_reviews_pkey PRIMARY KEY (id)
);
CREATE TABLE public.resume_builder_ratings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL UNIQUE,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  feedback text,
  user_agent text,
  device_type character varying CHECK (device_type::text = ANY (ARRAY['mobile'::character varying, 'tablet'::character varying, 'desktop'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT resume_builder_ratings_pkey PRIMARY KEY (id),
  CONSTRAINT resume_builder_ratings_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students_new(id)
);
CREATE TABLE public.resume_tracking (
  id uuid NOT NULL,
  resume_id uuid,
  resume_started boolean,
  resume_basic_info boolean,
  resume_basic_info_start_time timestamp without time zone,
  resume_basic_info_end_time timestamp without time zone,
  resume_work_exp boolean,
  resume_work_exp_start_time timestamp without time zone,
  resume_work_exp_end_time timestamp without time zone,
  resume_skills boolean,
  resume_skills_start_time timestamp without time zone,
  resume_skills_end_time timestamp without time zone,
  resume_education boolean,
  resume_education_start_time timestamp without time zone,
  resume_education_end_time timestamp without time zone,
  resume_review boolean,
  resume_review_start_time timestamp without time zone,
  resume_review_end_time timestamp without time zone,
  resume_downloaded boolean,
  used_count text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT resume_tracking_pkey PRIMARY KEY (id),
  CONSTRAINT resume_tracking_resume_id_fkey FOREIGN KEY (resume_id) REFERENCES public.static_resume_template(id)
);
CREATE TABLE public.role_based_resume_data (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid,
  role_based_resume_template_id uuid,
  resume_download_url text,
  resume_title text,
  resume_data json,
  created_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
  CONSTRAINT role_based_resume_data_pkey PRIMARY KEY (id),
  CONSTRAINT role_based_resume_data_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students_new(id),
  CONSTRAINT role_based_resume_data_role_based_resume_template_id_fkey FOREIGN KEY (role_based_resume_template_id) REFERENCES public.role_based_resume_template(id)
);
CREATE TABLE public.role_based_resume_template (
  id uuid NOT NULL,
  title text,
  tag ARRAY,
  rating text,
  preview_url text,
  template_data json,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT role_based_resume_template_pkey PRIMARY KEY (id)
);
CREATE TABLE public.session_payments (
  id uuid NOT NULL,
  student_id uuid,
  mentor_id uuid,
  session_id uuid,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT session_payments_pkey PRIMARY KEY (id),
  CONSTRAINT session_payments_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students_new(id),
  CONSTRAINT session_payments_mentor_id_fkey FOREIGN KEY (mentor_id) REFERENCES public.mentors_new(id),
  CONSTRAINT session_payments_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions(id)
);
CREATE TABLE public.sessions (
  id uuid NOT NULL,
  end_time text,
  start_time text,
  calculated_duration text,
  status text,
  is_rescheduled boolean,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT sessions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.skills (
  id uuid NOT NULL,
  skill_name text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT skills_pkey PRIMARY KEY (id)
);
CREATE TABLE public.static_resume_data (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  static_resume_id uuid,
  student_id uuid,
  personal_details json,
  education_details jsonb,
  work_exp_details jsonb,
  project_details jsonb,
  skills ARRAY,
  languages ARRAY,
  course_details jsonb,
  summary text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone,
  resume_url text,
  is_delete boolean DEFAULT false,
  CONSTRAINT static_resume_data_pkey PRIMARY KEY (id),
  CONSTRAINT static_resume_data_static_resume_id_fkey FOREIGN KEY (static_resume_id) REFERENCES public.static_resume_template(id),
  CONSTRAINT static_resume_data_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students_new(id)
);
CREATE TABLE public.static_resume_template (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text,
  tags ARRAY,
  rating text,
  preview_url text,
  template_data json,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  update_at timestamp with time zone,
  is_delete boolean DEFAULT false,
  views text,
  CONSTRAINT static_resume_template_pkey PRIMARY KEY (id)
);
CREATE TABLE public.student_feedback_response (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid,
  mentor_id uuid,
  slug text,
  feedback_response json,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  meeting_type_id uuid,
  CONSTRAINT student_feedback_response_pkey PRIMARY KEY (id),
  CONSTRAINT feedback_forms_meeting_type_id_fkey FOREIGN KEY (meeting_type_id) REFERENCES public.meeting_types(id),
  CONSTRAINT feedback_forms_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT feedback_forms_mentor_id_fkey FOREIGN KEY (mentor_id) REFERENCES public.mentors_new(id)
);
CREATE TABLE public.students (
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text,
  email text,
  phone text,
  resume text,
  id uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  mentor_url text,
  mentor_id uuid,
  event_type text,
  bot_id text,
  recording_url text,
  org_id uuid,
  start_time text,
  end_time text,
  date text,
  recorded_video_url text,
  amount text,
  transaction_id text,
  payment_status text,
  joined boolean,
  container_id text,
  batch text,
  institution text,
  job_description text,
  CONSTRAINT students_pkey PRIMARY KEY (id),
  CONSTRAINT students_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT students_mentor_id_fkey FOREIGN KEY (mentor_id) REFERENCES public.mentors_new(id)
);
CREATE TABLE public.students_new (
  id uuid NOT NULL DEFAULT auth.uid(),
  email text UNIQUE,
  phone text,
  profile_url text,
  first_name text,
  last_name text,
  address text,
  pincode text,
  state text,
  country text,
  highest_qualification text,
  highest_qualification_institute text,
  highest_qualification_subject text,
  career_interests ARRAY,
  need_help_in text,
  resume_url text,
  description text,
  student_priorities ARRAY,
  student_focus_area json,
  industry_updates ARRAY,
  job_opportunities json,
  project_opportunities json,
  master_resume_url ARRAY,
  saved_industry_updates ARRAY,
  liked_industry_updates ARRAY,
  static_resume_url text,
  role_based_resume_url text,
  is_delete boolean,
  is_suspended boolean,
  suspended_duration text,
  static_resume_data json,
  is_subscribe boolean,
  student_access_token text,
  student_referesh_token text,
  linkedin_url text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  saved_jobs ARRAY,
  org_id uuid,
  soft_skills ARRAY,
  technical_skills ARRAY,
  subscription_status text,
  autopay_reference text,
  last_payment_date text,
  profile_type text,
  education json,
  work_experience json,
  org_name text,
  is_data_filled boolean DEFAULT false,
  industry_subscription_end_date text,
  mentor_subscription_end_date text,
  reported_jobs ARRAY,
  report_job_reasons jsonb,
  saved_projects ARRAY,
  reported_projects ARRAY,
  report_project_reasons jsonb,
  saved_industry_news ARRAY,
  liked_industry_news ARRAY,
  institute_id uuid,
  certifications json,
  batch text,
  CONSTRAINT students_new_pkey PRIMARY KEY (id),
  CONSTRAINT students_new_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT students_new_institute_id_fkey FOREIGN KEY (institute_id) REFERENCES public.institutions(id)
);
CREATE TABLE public.students_subscription (
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  student_id uuid DEFAULT gen_random_uuid(),
  subscription_start_date text,
  subscription_end_date text,
  payment_status text,
  amount text,
  name text,
  email text,
  phone text,
  transaction_id text,
  subscription_type text,
  payment_date text,
  id uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  CONSTRAINT students_subscription_pkey PRIMARY KEY (id)
);
CREATE TABLE public.tcc_admins (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  full_name text NOT NULL,
  email text NOT NULL UNIQUE,
  phone text,
  role text DEFAULT 'admin'::text CHECK (role = ANY (ARRAY['super_admin'::text, 'admin'::text, 'sales'::text, 'operations'::text])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tcc_admins_pkey PRIMARY KEY (id),
  CONSTRAINT tcc_admins_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.test (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  bot_id text,
  video_url text,
  CONSTRAINT test_pkey PRIMARY KEY (id)
);
CREATE TABLE public.tickets (
  id uuid NOT NULL,
  subject text,
  category text,
  priority_level text,
  description text,
  attachments ARRAY,
  conversation_id uuid,
  read_time timestamp without time zone,
  status text,
  is_delete boolean,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT tickets_pkey PRIMARY KEY (id)
);
CREATE TABLE public.transaction (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  transaction_id text,
  payment_status boolean DEFAULT false,
  amount text,
  mentor_id uuid,
  updated_at timestamp with time zone,
  booking_id uuid UNIQUE,
  event_type text,
  start_time timestamp with time zone,
  end_time timestamp with time zone,
  CONSTRAINT transaction_pkey PRIMARY KEY (id),
  CONSTRAINT transaction_mentor_id_fkey FOREIGN KEY (mentor_id) REFERENCES public.mentors_new(id),
  CONSTRAINT transaction_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  user_name text,
  password text,
  role text DEFAULT ''::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  calendly_access_token text,
  calendly_refresh_token text,
  scheduling_url text,
  calendly_user_uri text,
  calendly_org_uri text,
  is_registered boolean NOT NULL DEFAULT false,
  availability_schedules jsonb,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.utilities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text UNIQUE,
  type text,
  CONSTRAINT utilities_pkey PRIMARY KEY (id)
);
CREATE TABLE public.utils (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  industry_filters text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  type text,
  CONSTRAINT utils_pkey PRIMARY KEY (id)
);
CREATE TABLE public.zoom_meetings (
  id integer NOT NULL DEFAULT nextval('zoom_meetings_id_seq'::regclass),
  student_email character varying NOT NULL,
  mentor_id character varying NOT NULL,
  calendly_event_id character varying NOT NULL UNIQUE,
  zoom_meeting_id character varying NOT NULL UNIQUE,
  zoom_join_url text NOT NULL,
  zoom_start_url text NOT NULL,
  meeting_topic character varying NOT NULL,
  meeting_start_time timestamp with time zone NOT NULL,
  meeting_duration integer NOT NULL DEFAULT 60,
  zoom_password character varying,
  status character varying DEFAULT 'scheduled'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT zoom_meetings_pkey PRIMARY KEY (id)
);